version: '3.7'
services:
  db:
    image: oracle/database:19.3.0-ee
    container_name: oracle
    ports:
      - 1521:1521
      - 5500:5500
    volumes:
      - ./data:/opt/oracle/oradata
    env_file: Environment.env           
